# Generated by Django 4.1.7 on 2023-02-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('кадастровый номер', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type_object', models.CharField(choices=[('BLD', 'Здание'), ('FLT', 'Квартира')], default='FLT', max_length=5)),
                ('адрес', models.CharField(blank=True, max_length=300)),
                ('паспорт загружен', models.BooleanField(default=False)),
                ('дата загрузки паспорта', models.DateField()),
                ('zip архив', models.FileField(upload_to='passports/')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'type_object': 'BLD'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='number.baseobject')),
            ],
        ),
    ]
