# Generated by Django 4.1.7 on 2023-02-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='кадастровый номер')),
                ('type_object', models.CharField(choices=[('BLD', 'Здание'), ('FLT', 'Квартира')], default='FLT', max_length=5, verbose_name='тип объекта')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес')),
                ('download', models.BooleanField(default=False, verbose_name='паспорт загружен')),
                ('date_of_download', models.DateField(blank=True, null=True, verbose_name='дата загрузки паспорта')),
                ('zip', models.FileField(blank=True, upload_to='passports/', verbose_name='zip архив')),
                ('url', models.URLField(blank=True, verbose_name='ссылка на файл')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'type_object': 'BLD'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='number.baseobject', verbose_name='здание')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
    ]
