# Generated by Django 4.1.7 on 2023-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseobject',
            name='zip архив',
            field=models.FileField(blank=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='дата загрузки паспорта',
            field=models.DateField(blank=True),
        ),
    ]
