# Generated by Django 4.1.7 on 2023-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0002_alter_baseobject_zip архив_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseobject',
            name='дата загрузки паспорта',
            field=models.DateField(blank=True, null=True),
        ),
    ]
