# Generated by Django 4.1.7 on 2023-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_alter_baseobject_дата загрузки паспорта'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseobject',
            name='zip архив',
        ),
        migrations.RemoveField(
            model_name='baseobject',
            name='адрес',
        ),
        migrations.RemoveField(
            model_name='baseobject',
            name='дата загрузки паспорта',
        ),
        migrations.RemoveField(
            model_name='baseobject',
            name='кадастровый номер',
        ),
        migrations.RemoveField(
            model_name='baseobject',
            name='паспорт загружен',
        ),
        migrations.AddField(
            model_name='baseobject',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='baseobject',
            name='date_of_download',
            field=models.DateField(blank=True, null=True, verbose_name='дата загрузки паспорта'),
        ),
        migrations.AddField(
            model_name='baseobject',
            name='download',
            field=models.BooleanField(default=False, verbose_name='паспорт загружен'),
        ),
        migrations.AddField(
            model_name='baseobject',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='кадастровый номер'),
        ),
        migrations.AddField(
            model_name='baseobject',
            name='zip',
            field=models.FileField(blank=True, upload_to='passports/', verbose_name='zip архив'),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='type_object',
            field=models.CharField(choices=[('BLD', 'Здание'), ('FLT', 'Квартира')], default='FLT', max_length=5, verbose_name='тип объекта'),
        ),
    ]
