# Generated by Django 4.1.7 on 2023-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_remove_baseobject_zip архив_remove_baseobject_адрес_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseobject',
            options={'verbose_name': 'объект', 'verbose_name_plural': 'объекты'},
        ),
        migrations.AddField(
            model_name='baseobject',
            name='url',
            field=models.URLField(blank=True, verbose_name='ссылка на файл'),
        ),
    ]
